import Menu from "@/components/Menu";
import "./globals.css";
import { Inter } from "next/font/google";
import FooterWithSitemap from "@/components/FooterWithSitemap";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex flex-col h-screen justify-between">
          <Menu className="h-10" />
          <div className=" mb-auto mx-10 h-full ">{children}</div>
          <FooterWithSitemap className="h-10" />
        </div>
      </body>
    </html>
  );
}
